/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateUpdatePingDto } from '../models';
import { DeletePingDto } from '../models';
/**
 * PingsApi - axios parameter creator
 * @export
 */
export const PingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new ping
         * @param {CreateUpdatePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsControllerAddPing: async (body: CreateUpdatePingDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling pingsControllerAddPing.');
            }
            const localVarPath = `/api/pings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a ping
         * @param {DeletePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsControllerDeletePing: async (body: DeletePingDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling pingsControllerDeletePing.');
            }
            const localVarPath = `/api/pings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a ping
         * @param {CreateUpdatePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsControllerUpdatePing: async (body: CreateUpdatePingDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling pingsControllerUpdatePing.');
            }
            const localVarPath = `/api/pings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PingsApi - functional programming interface
 * @export
 */
export const PingsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new ping
         * @param {CreateUpdatePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsControllerAddPing(body: CreateUpdatePingDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PingsApiAxiosParamCreator(configuration).pingsControllerAddPing(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete a ping
         * @param {DeletePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsControllerDeletePing(body: DeletePingDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await PingsApiAxiosParamCreator(configuration).pingsControllerDeletePing(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update a ping
         * @param {CreateUpdatePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsControllerUpdatePing(body: CreateUpdatePingDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CreateUpdatePingDto>>> {
            const localVarAxiosArgs = await PingsApiAxiosParamCreator(configuration).pingsControllerUpdatePing(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PingsApi - factory interface
 * @export
 */
export const PingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Add a new ping
         * @param {CreateUpdatePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsControllerAddPing(body: CreateUpdatePingDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PingsApiFp(configuration).pingsControllerAddPing(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a ping
         * @param {DeletePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsControllerDeletePing(body: DeletePingDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return PingsApiFp(configuration).pingsControllerDeletePing(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a ping
         * @param {CreateUpdatePingDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsControllerUpdatePing(body: CreateUpdatePingDto, options?: AxiosRequestConfig): Promise<AxiosResponse<CreateUpdatePingDto>> {
            return PingsApiFp(configuration).pingsControllerUpdatePing(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PingsApi - object-oriented interface
 * @export
 * @class PingsApi
 * @extends {BaseAPI}
 */
export class PingsApi extends BaseAPI {
    /**
     * 
     * @summary Add a new ping
     * @param {CreateUpdatePingDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PingsApi
     */
    public async pingsControllerAddPing(body: CreateUpdatePingDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PingsApiFp(this.configuration).pingsControllerAddPing(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete a ping
     * @param {DeletePingDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PingsApi
     */
    public async pingsControllerDeletePing(body: DeletePingDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return PingsApiFp(this.configuration).pingsControllerDeletePing(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update a ping
     * @param {CreateUpdatePingDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PingsApi
     */
    public async pingsControllerUpdatePing(body: CreateUpdatePingDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<CreateUpdatePingDto>> {
        return PingsApiFp(this.configuration).pingsControllerUpdatePing(body, options).then((request) => request(this.axios, this.basePath));
    }
}
