/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DiscordIdDto } from '../models';
import { GetChannelIdsResponseDto } from '../models';
import { LeaderboardEntryDto } from '../models';
import { PointsBalanceDto } from '../models';
import { UpdateSuccessDTO } from '../models';
/**
 * SuccessApi - axios parameter creator
 * @export
 */
export const SuccessApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get discord channel IDs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        successControllerGetChannelIds: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/success/ids`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the leaderboard for a guild
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        successControllerGetLeaderboard: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/success/leaderboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get success ledger info for a specific message ID
         * @param {string} userId The user to check for
         * @param {string} channelId The ID of the channel to fetch info from
         * @param {string} messageId The ID of the message to fetch info from
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        successControllerGetSuccessLedgerInfo: async (userId: string, channelId: string, messageId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling successControllerGetSuccessLedgerInfo.');
            }
            // verify required parameter 'channelId' is not null or undefined
            if (channelId === null || channelId === undefined) {
                throw new RequiredError('channelId','Required parameter channelId was null or undefined when calling successControllerGetSuccessLedgerInfo.');
            }
            // verify required parameter 'messageId' is not null or undefined
            if (messageId === null || messageId === undefined) {
                throw new RequiredError('messageId','Required parameter messageId was null or undefined when calling successControllerGetSuccessLedgerInfo.');
            }
            const localVarPath = `/api/success/ledger/{userId}/{channelId}/{messageId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"channelId"}}`, encodeURIComponent(String(channelId)))
                .replace(`{${"messageId"}}`, encodeURIComponent(String(messageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update or create success points for a user
         * @param {UpdateSuccessDTO} body The points and related info to update/create
         * @param {string} userId The ID of the user to update/create points for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        successControllerUpdatePoints: async (body: UpdateSuccessDTO, userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling successControllerUpdatePoints.');
            }
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling successControllerUpdatePoints.');
            }
            const localVarPath = `/api/success/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add or update discord channel IDs
         * @param {DiscordIdDto} body The channel id
         * @param {string} channelId The ID of the channel to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        successControllerUpsertChannelId: async (body: DiscordIdDto, channelId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling successControllerUpsertChannelId.');
            }
            // verify required parameter 'channelId' is not null or undefined
            if (channelId === null || channelId === undefined) {
                throw new RequiredError('channelId','Required parameter channelId was null or undefined when calling successControllerUpsertChannelId.');
            }
            const localVarPath = `/api/success/ids/{channelId}`
                .replace(`{${"channelId"}}`, encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SuccessApi - functional programming interface
 * @export
 */
export const SuccessApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get discord channel IDs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerGetChannelIds(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetChannelIdsResponseDto>>> {
            const localVarAxiosArgs = await SuccessApiAxiosParamCreator(configuration).successControllerGetChannelIds(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get the leaderboard for a guild
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerGetLeaderboard(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<LeaderboardEntryDto>>>> {
            const localVarAxiosArgs = await SuccessApiAxiosParamCreator(configuration).successControllerGetLeaderboard(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get success ledger info for a specific message ID
         * @param {string} userId The user to check for
         * @param {string} channelId The ID of the channel to fetch info from
         * @param {string} messageId The ID of the message to fetch info from
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerGetSuccessLedgerInfo(userId: string, channelId: string, messageId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await SuccessApiAxiosParamCreator(configuration).successControllerGetSuccessLedgerInfo(userId, channelId, messageId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update or create success points for a user
         * @param {UpdateSuccessDTO} body The points and related info to update/create
         * @param {string} userId The ID of the user to update/create points for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerUpdatePoints(body: UpdateSuccessDTO, userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PointsBalanceDto>>> {
            const localVarAxiosArgs = await SuccessApiAxiosParamCreator(configuration).successControllerUpdatePoints(body, userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Add or update discord channel IDs
         * @param {DiscordIdDto} body The channel id
         * @param {string} channelId The ID of the channel to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerUpsertChannelId(body: DiscordIdDto, channelId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SuccessApiAxiosParamCreator(configuration).successControllerUpsertChannelId(body, channelId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SuccessApi - factory interface
 * @export
 */
export const SuccessApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get discord channel IDs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerGetChannelIds(options?: AxiosRequestConfig): Promise<AxiosResponse<GetChannelIdsResponseDto>> {
            return SuccessApiFp(configuration).successControllerGetChannelIds(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the leaderboard for a guild
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerGetLeaderboard(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<LeaderboardEntryDto>>> {
            return SuccessApiFp(configuration).successControllerGetLeaderboard(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get success ledger info for a specific message ID
         * @param {string} userId The user to check for
         * @param {string} channelId The ID of the channel to fetch info from
         * @param {string} messageId The ID of the message to fetch info from
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerGetSuccessLedgerInfo(userId: string, channelId: string, messageId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return SuccessApiFp(configuration).successControllerGetSuccessLedgerInfo(userId, channelId, messageId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update or create success points for a user
         * @param {UpdateSuccessDTO} body The points and related info to update/create
         * @param {string} userId The ID of the user to update/create points for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerUpdatePoints(body: UpdateSuccessDTO, userId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PointsBalanceDto>> {
            return SuccessApiFp(configuration).successControllerUpdatePoints(body, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add or update discord channel IDs
         * @param {DiscordIdDto} body The channel id
         * @param {string} channelId The ID of the channel to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async successControllerUpsertChannelId(body: DiscordIdDto, channelId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SuccessApiFp(configuration).successControllerUpsertChannelId(body, channelId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SuccessApi - object-oriented interface
 * @export
 * @class SuccessApi
 * @extends {BaseAPI}
 */
export class SuccessApi extends BaseAPI {
    /**
     * 
     * @summary Get discord channel IDs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuccessApi
     */
    public async successControllerGetChannelIds(options?: AxiosRequestConfig) : Promise<AxiosResponse<GetChannelIdsResponseDto>> {
        return SuccessApiFp(this.configuration).successControllerGetChannelIds(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get the leaderboard for a guild
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuccessApi
     */
    public async successControllerGetLeaderboard(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<LeaderboardEntryDto>>> {
        return SuccessApiFp(this.configuration).successControllerGetLeaderboard(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get success ledger info for a specific message ID
     * @param {string} userId The user to check for
     * @param {string} channelId The ID of the channel to fetch info from
     * @param {string} messageId The ID of the message to fetch info from
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuccessApi
     */
    public async successControllerGetSuccessLedgerInfo(userId: string, channelId: string, messageId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return SuccessApiFp(this.configuration).successControllerGetSuccessLedgerInfo(userId, channelId, messageId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update or create success points for a user
     * @param {UpdateSuccessDTO} body The points and related info to update/create
     * @param {string} userId The ID of the user to update/create points for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuccessApi
     */
    public async successControllerUpdatePoints(body: UpdateSuccessDTO, userId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PointsBalanceDto>> {
        return SuccessApiFp(this.configuration).successControllerUpdatePoints(body, userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Add or update discord channel IDs
     * @param {DiscordIdDto} body The channel id
     * @param {string} channelId The ID of the channel to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SuccessApi
     */
    public async successControllerUpsertChannelId(body: DiscordIdDto, channelId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SuccessApiFp(this.configuration).successControllerUpsertChannelId(body, channelId, options).then((request) => request(this.axios, this.basePath));
    }
}
