/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BarcodeResponseDto } from '../models';
/**
 * UtilityApi - axios parameter creator
 * @export
 */
export const UtilityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Update or create user data
         * @param {string} upc The UPC to create a barcode for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerGetBarcodeImage: async (upc: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'upc' is not null or undefined
            if (upc === null || upc === undefined) {
                throw new RequiredError('upc','Required parameter upc was null or undefined when calling usersControllerGetBarcodeImage.');
            }
            const localVarPath = `/api/utility/barcode/{upc}`
                .replace(`{${"upc"}}`, encodeURIComponent(String(upc)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UtilityApi - functional programming interface
 * @export
 */
export const UtilityApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Update or create user data
         * @param {string} upc The UPC to create a barcode for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersControllerGetBarcodeImage(upc: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BarcodeResponseDto>>> {
            const localVarAxiosArgs = await UtilityApiAxiosParamCreator(configuration).usersControllerGetBarcodeImage(upc, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UtilityApi - factory interface
 * @export
 */
export const UtilityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Update or create user data
         * @param {string} upc The UPC to create a barcode for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersControllerGetBarcodeImage(upc: string, options?: AxiosRequestConfig): Promise<AxiosResponse<BarcodeResponseDto>> {
            return UtilityApiFp(configuration).usersControllerGetBarcodeImage(upc, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UtilityApi - object-oriented interface
 * @export
 * @class UtilityApi
 * @extends {BaseAPI}
 */
export class UtilityApi extends BaseAPI {
    /**
     * 
     * @summary Update or create user data
     * @param {string} upc The UPC to create a barcode for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UtilityApi
     */
    public async usersControllerGetBarcodeImage(upc: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<BarcodeResponseDto>> {
        return UtilityApiFp(this.configuration).usersControllerGetBarcodeImage(upc, options).then((request) => request(this.axios, this.basePath));
    }
}
