/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ZipcodeDto } from '../models';
/**
 * ZipcodesApi - axios parameter creator
 * @export
 */
export const ZipcodesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get zipcode data
         * @param {string} zipcode The zipcode to search for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        zipcodesControllerGetZipcode: async (zipcode: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'zipcode' is not null or undefined
            if (zipcode === null || zipcode === undefined) {
                throw new RequiredError('zipcode','Required parameter zipcode was null or undefined when calling zipcodesControllerGetZipcode.');
            }
            const localVarPath = `/api/zipcodes/{zipcode}`
                .replace(`{${"zipcode"}}`, encodeURIComponent(String(zipcode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ZipcodesApi - functional programming interface
 * @export
 */
export const ZipcodesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get zipcode data
         * @param {string} zipcode The zipcode to search for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async zipcodesControllerGetZipcode(zipcode: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ZipcodeDto>>> {
            const localVarAxiosArgs = await ZipcodesApiAxiosParamCreator(configuration).zipcodesControllerGetZipcode(zipcode, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ZipcodesApi - factory interface
 * @export
 */
export const ZipcodesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get zipcode data
         * @param {string} zipcode The zipcode to search for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async zipcodesControllerGetZipcode(zipcode: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ZipcodeDto>> {
            return ZipcodesApiFp(configuration).zipcodesControllerGetZipcode(zipcode, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ZipcodesApi - object-oriented interface
 * @export
 * @class ZipcodesApi
 * @extends {BaseAPI}
 */
export class ZipcodesApi extends BaseAPI {
    /**
     * 
     * @summary Get zipcode data
     * @param {string} zipcode The zipcode to search for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ZipcodesApi
     */
    public async zipcodesControllerGetZipcode(zipcode: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ZipcodeDto>> {
        return ZipcodesApiFp(this.configuration).zipcodesControllerGetZipcode(zipcode, options).then((request) => request(this.axios, this.basePath));
    }
}
