/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RoleInfoDto } from './role-info-dto';
 /**
 * 
 *
 * @export
 * @interface CategoryRolesDto
 */
export interface CategoryRolesDto {

    /**
     * @type {string}
     * @memberof CategoryRolesDto
     */
    messageId?: string;

    /**
     * @type {string}
     * @memberof CategoryRolesDto
     */
    guildId: string;

    /**
     * @type {string}
     * @memberof CategoryRolesDto
     */
    channelId?: string;

    /**
     * @type {Array<RoleInfoDto>}
     * @memberof CategoryRolesDto
     */
    roles: Array<RoleInfoDto>;
}
