/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUpdatePingDto
 */
export interface CreateUpdatePingDto {

    /**
     * @type {string}
     * @memberof CreateUpdatePingDto
     */
    channelId: string;

    /**
     * @type {boolean}
     * @memberof CreateUpdatePingDto
     */
    image?: boolean;
}
