/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GeometryDto
 */
export interface GeometryDto {

    /**
     * @type {Array<string>}
     * @memberof GeometryDto
     * @example [-118.4065,34.0901]
     */
    coordinates: Array<string>;

    /**
     * @type {string}
     * @memberof GeometryDto
     * @example Point
     */
    type: string;
}
