/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HDGlobalItemsStatsDto
 */
export interface HDGlobalItemsStatsDto {

    /**
     * Amount of stores this item is found in
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    foundInStores?: number;

    /**
     * Percent of stores this item is found in
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    foundInStoresPercent?: number;

    /**
     * Percentage of stores with the item on clearance
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    clearancePercentage?: number;

    /**
     * Average inventory across all stores
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    averageInventory?: number;

    /**
     * Lowest inventory amount among all stores
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    lowestInventory?: number;

    /**
     * Highest inventory amount among all stores
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    highestInventory?: number;

    /**
     * Average price of the item across all stores
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    averagePrice?: number;

    /**
     * Mode price of the item across all stores
     *
     * @type {string | number}
     * @memberof HDGlobalItemsStatsDto
     */
    modePrice?: string | number;

    /**
     * Lowest price of the item across all stores
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    lowestPrice?: number;

    /**
     * Highest price of the item across all stores
     *
     * @type {number}
     * @memberof HDGlobalItemsStatsDto
     */
    highestPrice?: number;
}
