/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HDMonitoredItemDto
 */
export interface HDMonitoredItemDto {

    /**
     * User who is monitoring the item
     *
     * @type {string}
     * @memberof HDMonitoredItemDto
     */
    userId: string;

    /**
     * Guild which the item is being monitored for
     *
     * @type {string}
     * @memberof HDMonitoredItemDto
     */
    guildId: string;

    /**
     * Store that it is being monitored at
     *
     * @type {string}
     * @memberof HDMonitoredItemDto
     */
    storeId: string;

    /**
     * Item that is being monitored
     *
     * @type {string}
     * @memberof HDMonitoredItemDto
     */
    itemId: string;

    /**
     * Brand of the item being monitored
     *
     * @type {string}
     * @memberof HDMonitoredItemDto
     */
    brand: string;

    /**
     * Name of the item being monitored
     *
     * @type {string}
     * @memberof HDMonitoredItemDto
     */
    name: string;

    /**
     * Msrp of the item being monitored
     *
     * @type {number}
     * @memberof HDMonitoredItemDto
     */
    msrp: number;

    /**
     * Image of the item being monitored
     *
     * @type {string}
     * @memberof HDMonitoredItemDto
     */
    image: string;

    /**
     * Item that is being monitored
     *
     * @type {number}
     * @memberof HDMonitoredItemDto
     */
    initialPrice: number;
}
