/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HDUpdateItemStatusDto
 */
export interface HDUpdateItemStatusDto {

    /**
     * Item search key
     *
     * @type {string}
     * @memberof HDUpdateItemStatusDto
     */
    searchKey: string;

    /**
     * Clearance status for the item
     *
     * @type {boolean}
     * @memberof HDUpdateItemStatusDto
     */
    isClearance: boolean;

    /**
     * As low as price
     *
     * @type {number}
     * @memberof HDUpdateItemStatusDto
     */
    buyAsLowAs: number;
}
