/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HoursDto
 */
export interface HoursDto {

    /**
     * @type {string}
     * @memberof HoursDto
     * @example 6:00
     */
    open: string;

    /**
     * @type {string}
     * @memberof HoursDto
     * @example 22:00
     */
    close: string;
}
