/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HoursDto } from './hours-dto';
 /**
 * 
 *
 * @export
 * @interface StoreHoursDto
 */
export interface StoreHoursDto {

    /**
     * @type {HoursDto}
     * @memberof StoreHoursDto
     */
    monday: HoursDto;

    /**
     * @type {HoursDto}
     * @memberof StoreHoursDto
     */
    tuesday: HoursDto;

    /**
     * @type {HoursDto}
     * @memberof StoreHoursDto
     */
    wednesday: HoursDto;

    /**
     * @type {HoursDto}
     * @memberof StoreHoursDto
     */
    thursday: HoursDto;

    /**
     * @type {HoursDto}
     * @memberof StoreHoursDto
     */
    friday: HoursDto;

    /**
     * @type {HoursDto}
     * @memberof StoreHoursDto
     */
    saturday: HoursDto;

    /**
     * @type {HoursDto}
     * @memberof StoreHoursDto
     */
    sunday: HoursDto;
}
