/* tslint:disable */
/* eslint-disable */
/**
 * Clearance API
 * Clearance.gg API docs for all the bots and monitors
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MapQuestResultDto } from './map-quest-result-dto';
 /**
 * 
 *
 * @export
 * @interface ZipcodeDto
 */
export interface ZipcodeDto {

    /**
     * @type {string}
     * @memberof ZipcodeDto
     * @example 90210
     */
    zipcode: string;

    /**
     * @type {number}
     * @memberof ZipcodeDto
     * @example 34.0901
     */
    lat: number;

    /**
     * @type {number}
     * @memberof ZipcodeDto
     * @example -118.4065
     */
    lng: number;

    /**
     * @type {string}
     * @memberof ZipcodeDto
     * @example America/Los_Angeles
     */
    ianaTimeZone: string;

    /**
     * @type {string}
     * @memberof ZipcodeDto
     * @example CA
     */
    state: string;

    /**
     * @type {string}
     * @memberof ZipcodeDto
     * @example PST
     */
    timeZoneAbbrevation: string;

    /**
     * @type {string}
     * @memberof ZipcodeDto
     * @example PDT
     */
    dstAbbrevation: string;

    /**
     * @type {string}
     * @memberof ZipcodeDto
     * @example UTC-8
     */
    offset: string;

    /**
     * @type {string}
     * @memberof ZipcodeDto
     * @example UTC-7
     */
    dstOffset: string;

    /**
     * @type {MapQuestResultDto}
     * @memberof ZipcodeDto
     */
    mapquestData: MapQuestResultDto;
}
